name: Backend Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  web-deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Code
      uses: actions/checkout@v3
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        local-dir: ./backend/
        server-dir: ina_trading_backend/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          
    - name: 📂 Execute deployment commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        script: |
          cd ina_trading_backend
          npm install
          npm run start 