name: Frontend Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  web-deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Code
      uses: actions/checkout@v3
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build
      run: |
        cd frontend
        npm run build
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        local-dir: ./frontend/build/
        server-dir: public_html/ 